SELECT 
    B.TITLE,
    B.BOARD_ID,
    R.REPLY_ID,
    R.WRITER_ID,
    R.CONTENTS,
    date_format(R.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
from USED_GOODS_BOARD B

JOIN USED_GOODS_REPLY R
on R.BOARD_ID = B.BOARD_ID

WHERE YEAR(B.CREATED_DATE) = 2022
  AND MONTH(B.CREATED_DATE) = 10
  
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC
;